# Render deployment configuration (optional)
# This file can be used to configure Render services via infrastructure as code

services:
  - type: web
    name: skyras-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
    # Add other environment variables in Render dashboard

